package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* lundi 20 octobre 2025 17 h 09 WEST
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
